[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
rocket = "0.5.0-rc.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"